Algoritmo "NomePessoa"

//2) Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de
//boasvindas para ela: Ex: Qual é o seu nome? João da Silva Olá João da Silva,
// é um prazer te conhecer!

Var
// Seção de Declarações das variáveis 
nome:caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual é o seu nome?")
leia(nome)

escreval("Olá ",nome," é um prazer te conhecer!")

Fimalgoritmo